const reactionResources = {
    OH: [ 'H', 'O' ],
    LH: [ 'H', 'L' ],
    KH: [ 'H', 'K' ],
    UH: [ 'H', 'U' ],
    ZH: [ 'H', 'Z' ],
    GH: [ 'H', 'G' ],
    LO: [ 'O', 'L' ],
    KO: [ 'O', 'K' ],
    UO: [ 'O', 'U' ],
    ZO: [ 'O', 'Z' ],
    GO: [ 'O', 'G' ],
    ZK: [ 'Z', 'K' ],
    UL: [ 'L', 'U' ],
    UH2O: [ 'OH', 'UH' ],
    UHO2: [ 'OH', 'UO' ],
    ZH2O: [ 'OH', 'ZH' ],
    ZHO2: [ 'OH', 'ZO' ],
    KH2O: [ 'OH', 'KH' ],
    KHO2: [ 'OH', 'KO' ],
    LH2O: [ 'OH', 'LH' ],
    LHO2: [ 'OH', 'LO' ],
    GH2O: [ 'OH', 'GH' ],
    GHO2: [ 'OH', 'GO' ],
    XUH2O: [ 'X', 'UH2O' ],
    XUHO2: [ 'X', 'UHO2' ],
    XLH2O: [ 'X', 'LH2O' ],
    XLHO2: [ 'X', 'LHO2' ],
    XKH2O: [ 'X', 'KH2O' ],
    XKHO2: [ 'X', 'KHO2' ],
    XZH2O: [ 'X', 'ZH2O' ],
    XZHO2: [ 'X', 'ZHO2' ],
    XGH2O: [ 'X', 'GH2O' ],
    XGHO2: [ 'X', 'GHO2' ],
    G: [ 'ZK', 'UL' ]
}

module.exports = reactionResources;